name: Deploy Develop Branch

on:
  push:
    branches:
      - develop
  workflow_dispatch:


jobs:
  deploy-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install express multer @supabase/supabase-js cors dotenv

      - name: Lint with ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create 'develop' folder on server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /var/www/deploy/${{github.ref_name}}"

      - name: Deploy to server
        run: scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/deploy/${{github.ref_name}}

      - name: Display deployed branch
        run: echo "Deployed branch ${{ github.ref_name }}"
