name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development
      DEPLOY_DIR: "/var/www/html/${{ github.ref_name }}" # crée un dossier selon la branche
      TOKEN: ${{ secrets.DEVOIRS6_TOKEN }} # À stocker dans GitHub Secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run unit tests
        run: npm run test:unit

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Migrate database
        run: |
          if [ -f "./scripts/migrate.sh" ]; then
            chmod +x ./scripts/migrate.sh
            ./scripts/migrate.sh
          else
            echo "No migration script found, skipping."
          fi

      - name: Deploy to server
        run: |
          ssh user@your-server "mkdir -p $DEPLOY_DIR"
          rsync -avz --delete ./dist/ user@your-server:$DEPLOY_DIR

      - name: Display deployed branch on site
        run: echo "${{ github.ref_name }}" > deployed-branch.txt && rsync deployed-branch.txt user@your-server:$DEPLOY_DIR/

