
name: Deploy Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  deploy-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Créer le dossier 'develop' sur le serveur distant
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /var/www/develop"

      - name: Copier les fichiers sur le serveur distant
        run: scp -r ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/develop

      - name: Installer les dépendances
        run: npm install

      - name: Linter le code avec ESLint
        run: npm run lint

      - name: Exécuter les tests unitaires
        run: npm run test:unit

      - name: Exécuter les tests E2E
        run: npm run test:e2e

      - name: Migrer la base de données
        run: npm run migrate

      - name: Afficher la branche déployée
        run: echo "${{ github.ref_name }}" > deployed_branch.txt && scp deployed_branch.txt ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/develop/version.txt
