name: CI/CD Pipeline for Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Permet de déclencher manuellement la pipeline

jobs:
  deploy:
    name: Deploy to Develop Folder
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, e2e-tests, migrate-db]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy Application to Develop Folder
        env:
          BRANCH_NAME: ${{ github.ref_name }} # Nom de la branche
        run: |
          echo "Deploying branch $BRANCH_NAME"
          mkdir -p /var/www/develop/$BRANCH_NAME # Crée un dossier pour la branche
          cp -r * /var/www/develop/$BRANCH_NAME # Copie les fichiers dans le dossier

      - name: Display Deployed Branch
        run: |
          echo "Deployed branch: ${{ github.ref_name }}"
