name: CI/CD Pipeline for Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Permet de déclencher manuellement la pipeline

jobs:
  lint:
    name: Lint Code with ESLint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

  deploy:
    name: Deploy to Develop Folder
    runs-on: ubuntu-latest
    needs: [lint, unit-tests] # Même si les jobs échouent, ils ne bloquent pas le déploiement
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy Application to Develop Folder
        env:
          BRANCH_NAME: ${{ github.ref_name }} # Nom de la branche
          DEPLOY_PATH: "/var/www/develop/${{ github.ref_name }}"
        run: |
          echo "Deploying branch $BRANCH_NAME"
          mkdir -p "$DEPLOY_PATH" # Crée un dossier pour la branche
          cp -r ./* "$DEPLOY_PATH" # Copie les fichiers dans le dossier

      - name: Display Deployed Branch
        run: echo "Deployed branch: ${{ github.ref_name }}"