name: Main Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Kill existing server processes
        run: fuser -k 5173/tcp || true

      - name: Start server
        run: npm run dev & npx wait-on http://localhost:5173

      - name: Run E2E tests
        run: npm run e2e