name: Main Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  unit_tests:
    name: Run Unit Tests
    needs: [lint]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  e2e_tests: 
    name: Run End-to-End Tests
    needs: [unit_tests]
    runs-on: ubuntu-latest
    timeout-minutes: 45
    continue-on-error: true  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --global user.email "diangou.cmr09@gmail.com"
          git config --global user.name "CI/CD"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run smoke tests
        run: npx playwright test --project=chromium --grep @smoke

      - name: Run other tests
        run: npx playwright test --project=chromium --grep-invert @smoke

  deploy:
    name: Deploy to Vercel
    needs: [e2e_tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Vercel  
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.DEVOIRS6_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
