name: Main Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: |
            ${{ runner.os }}-playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Check API availability
        run: curl --retry 5 --retry-delay 10 --fail https://tyradex.vercel.app/api/v1/pokemon/25 || exit 1

      - name: Wait before running tests
        run: sleep 10  # Attendre quelques secondes pour éviter les blocages

      - name: Run E2E tests
        run: npx playwright test --workers=4 --timeout=90000
        env:
          PWDEBUG: 0
          PLAYWRIGHT_TEST_TIMEOUT: 120000