e2e_tests: 
  name: Playwright Tests
  needs: [unit_tests]
  runs-on: ubuntu-latest
  timeout-minutes: 45
  continue-on-error: true  

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Configure Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "CI/CD"

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run smoke tests
      run: npx playwright test --project=chromium --grep @smoke --reporter=dot,html

    - name: Run other tests
      run: npx playwright test --project=chromium --grep-invert @smoke --reporter=dot,html

    # Upload HTML report only if tests failed
    - name: Upload Playwright HTML report on failure
      if: failure() && !cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-html-report
        path: playwright-report/
        retention-days: 30
