name: Vitest Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest with HTML report
        run: npx vitest run

      - name: Upload Vitest HTML Report
        if: always() # même si tests échouent
        uses: actions/upload-artifact@v4
        with:
          name: vitest-html-report
          path: vitest-report/
          retention-days: 30
